(function(){
  const DATA=window.BFUTR_DATA;
  const participants=DATA.participants;
  const byId=new Map(participants.map(p=>[p.id,p]));
  const state={mode:'single',race:'ALL',a:null,b:null};
  const $=sel=>document.querySelector(sel);
  const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const fmtTime=sec=>{if(sec==null||Number.isNaN(sec))return '–';let t=Math.round(sec*10);const d=t%10;t=Math.floor(t/10);const h=Math.floor(t/3600);const m=Math.floor((t%3600)/60);const s=t%60;return (h?h+':':'')+(h?String(m).padStart(2,'0'):m)+':'+String(s).padStart(2,'0')+','+d;};
  const fmtDelta=sec=>{if(sec==null)return '–';const sign=sec>0?'+':sec<0?'−':'';return sign+fmtTime(Math.abs(sec));};
  const splitMap=p=>Object.fromEntries(p.splits.map(s=>[s.checkpoint,s]));
  const statusBadge=p=>p.status==='Finish'?'<span class="badge">Finish</span>':p.status==='Kein Zielresultat'?'<span class="badge warn">Kein Zielresultat</span>':'<span class="badge muted">Keine Messzeit</span>';
  const rankText=(rank,field)=>rank?('#'+rank+' / '+field):'–';
  const pct=(a,b)=>b?((a/b-1)*100):null;
  const medianSection=(race,a,b)=>{const x=DATA.benchmarks[race]&&DATA.benchmarks[race].section[a+' → '+b];return x?x.medianSec:null;};
  const raceOrder=r=>DATA.raceOrders[r]||[];
  const lastSplit=p=>{const m=splitMap(p);const order=raceOrder(p.race);for(let i=order.length-1;i>=0;i--){if(m[order[i]])return m[order[i]];}return null;};
  function profileStats(p){const last=lastSplit(p);return [
    ['Zielzeit',p.officialFinisher?fmtTime(p.finalSec):'–'],
    ['Rang gesamt',rankText(p.finishRankOverall,p.finishFieldOverall)],
    [p.gender==='Offen'?'Kategorie':p.gender,rankText(p.finishRankGender,p.finishFieldGender)],
    ['Letzter Messpunkt',last?(last.checkpoint+' · '+fmtTime(last.sec)):'–'],
    ['Messpunkte',p.splits.length+' / '+raceOrder(p.race).length]
  ];}
  function renderProfileHeader(p){return '<div class="profile-card card"><div class="profile-top"><div class="profile-name"><span class="section-kicker">'+esc(p.race)+' · Startnr. '+esc(p.bib)+'</span><h2>'+esc(p.displayName)+'</h2><div class="meta-line">'+esc(p.gender)+(p.club?' · '+esc(p.club):'')+'</div></div>'+statusBadge(p)+'</div><div class="stats-grid">'+profileStats(p).map(x=>'<div class="stat"><span>'+esc(x[0])+'</span><strong>'+esc(x[1])+'</strong></div>').join('')+'</div></div>';}
  function sectionRows(p){const order=raceOrder(p.race),m=splitMap(p),rows=[];for(let i=1;i<order.length;i++){const a=order[i-1],b=order[i];if(!m[a]||!m[b])continue;const sec=m[b].sec-m[a].sec,med=medianSection(p.race,a,b);rows.push({label:a+' → '+b,sec,med,diffPct:pct(sec,med)});}return rows;}
  function renderBars(p){const rows=sectionRows(p);if(!rows.length)return '<div class="empty-state">Noch nicht genug aufeinanderfolgende Messpunkte für eine Abschnittsanalyse.</div>';const max=Math.max(10,...rows.map(r=>Math.abs(r.diffPct||0)));return '<div class="section-bars">'+rows.map(r=>{const width=Math.min(48,Math.abs(r.diffPct||0)/max*48);const cls=(r.diffPct||0)<=0?'faster':'slower';const val=r.diffPct==null?'–':((r.diffPct>0?'+':'')+r.diffPct.toFixed(1).replace('.',',')+' %');return '<div class="section-row"><div class="section-label">'+esc(r.label)+'</div><div class="bar-track"><div class="bar-fill '+cls+'" style="width:'+width+'%"></div></div><div class="section-value '+((r.diffPct||0)<=0?'positive':'negative')+'">'+val+'</div></div>';}).join('')+'</div>';}
  function renderRankChart(p){const pts=p.splits.filter(s=>s.rankOverall).map(s=>({label:s.checkpoint,value:s.rankOverall,field:s.fieldOverall}));if(pts.length<2)return '<div class="empty-state">Noch nicht genug Rangpunkte vorhanden.</div>';const w=Math.max(640,pts.length*88),h=300,pad={l:46,r:20,t:28,b:72};const vals=pts.map(x=>x.value),min=Math.min(...vals),max=Math.max(...vals),span=Math.max(4,max-min);const y=v=>pad.t+(v-(min-1))/(span+2)*(h-pad.t-pad.b);const x=i=>pad.l+i*((w-pad.l-pad.r)/(pts.length-1));const line=pts.map((p,i)=>x(i)+','+y(p.value)).join(' ');return '<svg viewBox="0 0 '+w+' '+h+'" role="img" aria-label="Rangverlauf"><line x1="'+pad.l+'" y1="'+(h-pad.b)+'" x2="'+(w-pad.r)+'" y2="'+(h-pad.b)+'" stroke="#d9e0d8"/><polyline points="'+line+'" fill="none" stroke="#2f6b4d" stroke-width="3" stroke-linejoin="round"/>'+pts.map((p,i)=>'<g><circle cx="'+x(i)+'" cy="'+y(p.value)+'" r="5" fill="#173d2d"/><text x="'+x(i)+'" y="'+(y(p.value)-10)+'" text-anchor="middle" font-size="12" font-weight="700" fill="#172019">#'+p.value+'</text><text transform="translate('+x(i)+' '+(h-pad.b+20)+') rotate(-35)" text-anchor="end" font-size="11" fill="#657066">'+esc(p.label)+'</text></g>').join('')+'</svg>';}
  function renderSplitTable(p){const order=raceOrder(p.race),m=splitMap(p);let prev=null;const rows=order.map(cp=>{const s=m[cp];if(!s)return '';let section='–',vs='–';if(prev&&m[prev]){const sec=s.sec-m[prev].sec,med=medianSection(p.race,prev,cp);section=fmtTime(sec);if(med){const d=pct(sec,med);vs='<span class="'+(d<=0?'positive':'negative')+'">'+(d>0?'+':'')+d.toFixed(1).replace('.',',')+' %</span>';}}prev=cp;return '<tr><td><strong>'+esc(cp)+'</strong></td><td class="num">'+fmtTime(s.sec)+'</td><td class="num">'+section+'</td><td class="num">'+rankText(s.rankOverall,s.fieldOverall)+'</td><td class="num">'+rankText(s.rankGender,s.fieldGender)+'</td><td class="num">'+vs+'</td></tr>';}).join('');return '<div class="table-card card"><div class="table-head"><h3>Alle Zwischenzeiten</h3><p class="panel-sub">Ränge beziehen sich auf Personen mit einer echten Messung am jeweiligen Checkpoint.</p></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Messpunkt</th><th>Passage</th><th>Abschnitt</th><th>Rang gesamt</th><th>'+esc(p.gender)+'</th><th>Abschnitt vs. Median</th></tr></thead><tbody>'+rows+'</tbody></table></div></div>';}
  function renderSingle(){const root=$('#singleView'),p=byId.get(state.a);if(!p){root.innerHTML='<div class="card empty-state">Wähle eine Person aus, um die Analyse zu öffnen.</div>';return;}root.innerHTML=renderProfileHeader(p)+'<div class="grid-2"><div class="panel card"><h3>Rangverlauf</h3><p class="panel-sub">Position unter allen Personen mit Messung am jeweiligen Checkpoint.</p><div class="chart-scroll"><div class="chart-host">'+renderRankChart(p)+'</div></div></div><div class="panel card"><h3>Abschnitte vs. Feldmedian</h3><p class="panel-sub">Links/grün = schneller als Median, rechts/orange = langsamer.</p>'+renderBars(p)+'</div></div>'+renderSplitTable(p);}
  function compareCard(p,label){return '<div class="compare-person card"><span class="section-kicker">'+label+' · '+esc(p.race)+'</span><h2>'+esc(p.displayName)+'</h2>'+statusBadge(p)+'<div class="compare-kpis"><div><span>Zielzeit</span><strong>'+(p.officialFinisher?fmtTime(p.finalSec):'–')+'</strong></div><div><span>Gesamtrang</span><strong>'+rankText(p.finishRankOverall,p.finishFieldOverall)+'</strong></div><div><span>Startnr.</span><strong>'+esc(p.bib)+'</strong></div><div><span>Letzter Punkt</span><strong>'+(lastSplit(p)?esc(lastSplit(p).checkpoint):'–')+'</strong></div></div></div>';}
  function renderDeltaChart(a,b,common){if(common.length<2)return '<div class="empty-state">Zu wenige gemeinsame Messpunkte.</div>';const ma=splitMap(a),mb=splitMap(b),pts=common.map(cp=>({label:cp,value:mb[cp].sec-ma[cp].sec}));const w=Math.max(640,pts.length*90),h=300,pad={l:54,r:20,t:30,b:72};const maxAbs=Math.max(30,...pts.map(p=>Math.abs(p.value)));const x=i=>pad.l+i*((w-pad.l-pad.r)/(pts.length-1));const y=v=>pad.t+(maxAbs-v)/(2*maxAbs)*(h-pad.t-pad.b);const zero=y(0);return '<svg viewBox="0 0 '+w+' '+h+'" role="img" aria-label="Zeitabstand"><line x1="'+pad.l+'" y1="'+zero+'" x2="'+(w-pad.r)+'" y2="'+zero+'" stroke="#9ba69c" stroke-dasharray="4 4"/><polyline points="'+pts.map((p,i)=>x(i)+','+y(p.value)).join(' ')+'" fill="none" stroke="#2f6b4d" stroke-width="3"/>'+pts.map((p,i)=>'<g><circle cx="'+x(i)+'" cy="'+y(p.value)+'" r="5" fill="#173d2d"/><text x="'+x(i)+'" y="'+(y(p.value)+(p.value>=0?-11:19))+'" text-anchor="middle" font-size="11" font-weight="700" fill="#172019">'+fmtDelta(p.value)+'</text><text transform="translate('+x(i)+' '+(h-pad.b+20)+') rotate(-35)" text-anchor="end" font-size="11" fill="#657066">'+esc(p.label)+'</text></g>').join('')+'</svg>';}
  function renderCompare(){const root=$('#compareView'),a=byId.get(state.a),b=byId.get(state.b);if(!a||!b){root.innerHTML='<div class="card empty-state">Wähle zwei Personen für den Vergleich aus.</div>';return;}const ma=splitMap(a),mb=splitMap(b);let order=a.race===b.race?raceOrder(a.race):raceOrder(a.race).concat(raceOrder(b.race).filter(x=>!raceOrder(a.race).includes(x)));const common=order.filter(cp=>ma[cp]&&mb[cp]);let passageRows=common.map(cp=>{const d=mb[cp].sec-ma[cp].sec;return '<tr><td><strong>'+esc(cp)+'</strong></td><td class="num">'+fmtTime(ma[cp].sec)+'</td><td class="num">'+fmtTime(mb[cp].sec)+'</td><td class="num '+(d>=0?'positive':'negative')+'">'+(d>=0?esc(a.displayName)+' '+fmtTime(d)+' voraus':esc(b.displayName)+' '+fmtTime(-d)+' voraus')+'</td></tr>';}).join('');let sectionRows=[];for(let i=1;i<common.length;i++){const p=common[i-1],c=common[i],sa=ma[c].sec-ma[p].sec,sb=mb[c].sec-mb[p].sec,d=sb-sa;sectionRows.push('<tr><td><strong>'+esc(p+' → '+c)+'</strong></td><td class="num">'+fmtTime(sa)+'</td><td class="num">'+fmtTime(sb)+'</td><td class="num '+(d>=0?'positive':'negative')+'">'+(d>=0?esc(a.displayName)+' '+fmtTime(d)+' schneller':esc(b.displayName)+' '+fmtTime(-d)+' schneller')+'</td></tr>');}root.innerHTML='<div class="compare-summary">'+compareCard(a,'Person A')+'<div class="versus">VS</div>'+compareCard(b,'Person B')+'</div>'+(a.race!==b.race?'<div class="notice">Die beiden Personen liefen unterschiedliche Distanzen. Verglichen werden deshalb nur Messpunkte, die in beiden Datensätzen vorkommen.</div>':'')+'<div class="panel card"><h3>Zeitabstand im Rennverlauf</h3><p class="panel-sub">Positive Werte bedeuten: '+esc(a.displayName)+' liegt vor '+esc(b.displayName)+'.</p><div class="chart-scroll"><div class="chart-host">'+renderDeltaChart(a,b,common)+'</div></div></div><div class="table-card card"><div class="table-head"><h3>Gemeinsame Passagezeiten</h3></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Messpunkt</th><th>'+esc(a.displayName)+'</th><th>'+esc(b.displayName)+'</th><th>Abstand</th></tr></thead><tbody>'+passageRows+'</tbody></table></div></div><div class="table-card card"><div class="table-head"><h3>Abschnitt für Abschnitt</h3></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Abschnitt</th><th>'+esc(a.displayName)+'</th><th>'+esc(b.displayName)+'</th><th>Schneller</th></tr></thead><tbody>'+sectionRows.join('')+'</tbody></table></div></div>';}
  function picker(rootSel,key){const root=$(rootSel),input=root.querySelector('input'),box=root.querySelector('.picker-results');function list(q){q=(q||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();let arr=participants.filter(p=>(state.race==='ALL'||p.race===state.race)&&(!q||p.search.includes(q))).slice(0,10);box.innerHTML=arr.map(p=>'<div class="picker-option" role="option" data-id="'+p.id+'"><strong>'+esc(p.displayName)+'</strong><span>'+esc(p.race)+' · #'+esc(p.bib)+' · '+esc(p.status)+'</span></div>').join('')||'<div class="picker-option"><span>Keine Treffer</span></div>';box.classList.add('open');input.setAttribute('aria-expanded','true');}input.addEventListener('input',()=>list(input.value));input.addEventListener('focus',()=>list(input.value));box.addEventListener('mousedown',e=>{const opt=e.target.closest('[data-id]');if(!opt)return;e.preventDefault();state[key]=opt.dataset.id;input.value=byId.get(state[key]).displayName;box.classList.remove('open');input.setAttribute('aria-expanded','false');syncUrl();render();});document.addEventListener('click',e=>{if(!root.contains(e.target)){box.classList.remove('open');input.setAttribute('aria-expanded','false');}});return {set(id){const p=byId.get(id);input.value=p?p.displayName:'';}};}
  const pickerA=picker('#personAPicker','a'),pickerB=picker('#personBPicker','b');
  function syncUrl(){const u=new URL(location.href);u.searchParams.set('mode',state.mode);if(state.race==='ALL')u.searchParams.delete('race');else u.searchParams.set('race',state.race);state.a?u.searchParams.set('a',state.a):u.searchParams.delete('a');state.b?u.searchParams.set('b',state.b):u.searchParams.delete('b');history.replaceState(null,'',u);}
  function render(){const compare=state.mode==='compare';$('#singleTab').classList.toggle('active',!compare);$('#compareTab').classList.toggle('active',compare);$('#singleTab').setAttribute('aria-selected',String(!compare));$('#compareTab').setAttribute('aria-selected',String(compare));$('#pickerGrid').classList.toggle('single-mode',!compare);$('#singleView').classList.toggle('hidden',compare);$('#compareView').classList.toggle('hidden',!compare);pickerA.set(state.a);pickerB.set(state.b);if(compare)renderCompare();else renderSingle();}
  function init(){const races=Object.keys(DATA.raceMeta);$('#raceFilter').innerHTML='<option value="ALL">Alle Distanzen</option>'+races.map(r=>'<option value="'+esc(r)+'">'+esc(r)+'</option>').join('');$('#metricParticipants').textContent=DATA.participantCount.toLocaleString('de-DE');$('#metricRaces').textContent=races.length;$('#metricSplits').textContent=participants.reduce((n,p)=>n+p.splits.length,0).toLocaleString('de-DE');$('#dataNote').textContent=DATA.dataNote;const params=new URLSearchParams(location.search);state.mode=params.get('mode')==='compare'?'compare':'single';state.race=races.includes(params.get('race'))?params.get('race'):'ALL';const fav=DATA.favorites.map(id=>byId.get(id)).filter(Boolean);state.a=byId.has(params.get('a'))?params.get('a'):(fav[0]&&fav[0].id);state.b=byId.has(params.get('b'))?params.get('b'):(fav[1]&&fav[1].id);$('#raceFilter').value=state.race;$('#favoriteButtons').innerHTML=fav.map(p=>'<button type="button" data-id="'+p.id+'">'+esc(p.displayName)+'</button>').join('');$('#favoriteButtons').addEventListener('click',e=>{const btn=e.target.closest('[data-id]');if(!btn)return;if(state.mode==='compare'){if(!state.a||state.a===state.b)state.a=btn.dataset.id;else state.b=btn.dataset.id;}else state.a=btn.dataset.id;syncUrl();render();});$('#raceFilter').addEventListener('change',e=>{state.race=e.target.value;if(state.race!=='ALL'){if(state.a&&byId.get(state.a).race!==state.race)state.a=null;if(state.b&&byId.get(state.b).race!==state.race)state.b=null;}syncUrl();render();});$('#singleTab').addEventListener('click',()=>{state.mode='single';syncUrl();render();});$('#compareTab').addEventListener('click',()=>{state.mode='compare';syncUrl();render();});render();}
  init();
})();
